/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum calificacion_c implements org.apache.avro.generic.GenericEnumSymbol<calificacion_c> {
  A, B, C, D, E  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"calificacion_c\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"A\",\"B\",\"C\",\"D\",\"E\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
