/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Demografico extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8497709867316443050L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Demografico\",\"namespace\":\"co.com.muric.entities.model.avro\",\"fields\":[{\"name\":\"identificacion_credito_entidad\",\"type\":\"string\"},{\"name\":\"tipo_identificacion\",\"type\":{\"type\":\"enum\",\"name\":\"tipo_ident\",\"symbols\":[\"_0\",\"_1\",\"_2\",\"_3\",\"_4\",\"_5\",\"_6\",\"_7\",\"_8\",\"_9\",\"_10\",\"_11\",\"_12\",\"_13\",\"_14\",\"_15\",\"_16\",\"_17\",\"_18\",\"_19\",\"_20\",\"_21\",\"_22\",\"_23\",\"_24\",\"_25\",\"_26\",\"_27\",\"_28\",\"_29\",\"_30\"]}},{\"name\":\"numero_identificacion\",\"type\":\"string\"},{\"name\":\"clave_atributo\",\"type\":\"int\"},{\"name\":\"valor_atributo\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Demografico> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Demografico> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Demografico> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Demografico> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Demografico> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Demografico to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Demografico from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Demografico instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Demografico fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence identificacion_credito_entidad;
  private co.com.muric.entities.model.avro.tipo_ident tipo_identificacion;
  private java.lang.CharSequence numero_identificacion;
  private int clave_atributo;
  private java.lang.CharSequence valor_atributo;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Demografico() {}

  /**
   * All-args constructor.
   * @param identificacion_credito_entidad The new value for identificacion_credito_entidad
   * @param tipo_identificacion The new value for tipo_identificacion
   * @param numero_identificacion The new value for numero_identificacion
   * @param clave_atributo The new value for clave_atributo
   * @param valor_atributo The new value for valor_atributo
   */
  public Demografico(java.lang.CharSequence identificacion_credito_entidad, co.com.muric.entities.model.avro.tipo_ident tipo_identificacion, java.lang.CharSequence numero_identificacion, java.lang.Integer clave_atributo, java.lang.CharSequence valor_atributo) {
    this.identificacion_credito_entidad = identificacion_credito_entidad;
    this.tipo_identificacion = tipo_identificacion;
    this.numero_identificacion = numero_identificacion;
    this.clave_atributo = clave_atributo;
    this.valor_atributo = valor_atributo;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return identificacion_credito_entidad;
    case 1: return tipo_identificacion;
    case 2: return numero_identificacion;
    case 3: return clave_atributo;
    case 4: return valor_atributo;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: identificacion_credito_entidad = (java.lang.CharSequence)value$; break;
    case 1: tipo_identificacion = (co.com.muric.entities.model.avro.tipo_ident)value$; break;
    case 2: numero_identificacion = (java.lang.CharSequence)value$; break;
    case 3: clave_atributo = (java.lang.Integer)value$; break;
    case 4: valor_atributo = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'identificacion_credito_entidad' field.
   * @return The value of the 'identificacion_credito_entidad' field.
   */
  public java.lang.CharSequence getIdentificacionCreditoEntidad() {
    return identificacion_credito_entidad;
  }


  /**
   * Sets the value of the 'identificacion_credito_entidad' field.
   * @param value the value to set.
   */
  public void setIdentificacionCreditoEntidad(java.lang.CharSequence value) {
    this.identificacion_credito_entidad = value;
  }

  /**
   * Gets the value of the 'tipo_identificacion' field.
   * @return The value of the 'tipo_identificacion' field.
   */
  public co.com.muric.entities.model.avro.tipo_ident getTipoIdentificacion() {
    return tipo_identificacion;
  }


  /**
   * Sets the value of the 'tipo_identificacion' field.
   * @param value the value to set.
   */
  public void setTipoIdentificacion(co.com.muric.entities.model.avro.tipo_ident value) {
    this.tipo_identificacion = value;
  }

  /**
   * Gets the value of the 'numero_identificacion' field.
   * @return The value of the 'numero_identificacion' field.
   */
  public java.lang.CharSequence getNumeroIdentificacion() {
    return numero_identificacion;
  }


  /**
   * Sets the value of the 'numero_identificacion' field.
   * @param value the value to set.
   */
  public void setNumeroIdentificacion(java.lang.CharSequence value) {
    this.numero_identificacion = value;
  }

  /**
   * Gets the value of the 'clave_atributo' field.
   * @return The value of the 'clave_atributo' field.
   */
  public int getClaveAtributo() {
    return clave_atributo;
  }


  /**
   * Sets the value of the 'clave_atributo' field.
   * @param value the value to set.
   */
  public void setClaveAtributo(int value) {
    this.clave_atributo = value;
  }

  /**
   * Gets the value of the 'valor_atributo' field.
   * @return The value of the 'valor_atributo' field.
   */
  public java.lang.CharSequence getValorAtributo() {
    return valor_atributo;
  }


  /**
   * Sets the value of the 'valor_atributo' field.
   * @param value the value to set.
   */
  public void setValorAtributo(java.lang.CharSequence value) {
    this.valor_atributo = value;
  }

  /**
   * Creates a new Demografico RecordBuilder.
   * @return A new Demografico RecordBuilder
   */
  public static co.com.muric.entities.model.avro.Demografico.Builder newBuilder() {
    return new co.com.muric.entities.model.avro.Demografico.Builder();
  }

  /**
   * Creates a new Demografico RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Demografico RecordBuilder
   */
  public static co.com.muric.entities.model.avro.Demografico.Builder newBuilder(co.com.muric.entities.model.avro.Demografico.Builder other) {
    if (other == null) {
      return new co.com.muric.entities.model.avro.Demografico.Builder();
    } else {
      return new co.com.muric.entities.model.avro.Demografico.Builder(other);
    }
  }

  /**
   * Creates a new Demografico RecordBuilder by copying an existing Demografico instance.
   * @param other The existing instance to copy.
   * @return A new Demografico RecordBuilder
   */
  public static co.com.muric.entities.model.avro.Demografico.Builder newBuilder(co.com.muric.entities.model.avro.Demografico other) {
    if (other == null) {
      return new co.com.muric.entities.model.avro.Demografico.Builder();
    } else {
      return new co.com.muric.entities.model.avro.Demografico.Builder(other);
    }
  }

  /**
   * RecordBuilder for Demografico instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Demografico>
    implements org.apache.avro.data.RecordBuilder<Demografico> {

    private java.lang.CharSequence identificacion_credito_entidad;
    private co.com.muric.entities.model.avro.tipo_ident tipo_identificacion;
    private java.lang.CharSequence numero_identificacion;
    private int clave_atributo;
    private java.lang.CharSequence valor_atributo;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(co.com.muric.entities.model.avro.Demografico.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.identificacion_credito_entidad)) {
        this.identificacion_credito_entidad = data().deepCopy(fields()[0].schema(), other.identificacion_credito_entidad);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tipo_identificacion)) {
        this.tipo_identificacion = data().deepCopy(fields()[1].schema(), other.tipo_identificacion);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.numero_identificacion)) {
        this.numero_identificacion = data().deepCopy(fields()[2].schema(), other.numero_identificacion);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.clave_atributo)) {
        this.clave_atributo = data().deepCopy(fields()[3].schema(), other.clave_atributo);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.valor_atributo)) {
        this.valor_atributo = data().deepCopy(fields()[4].schema(), other.valor_atributo);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Demografico instance
     * @param other The existing instance to copy.
     */
    private Builder(co.com.muric.entities.model.avro.Demografico other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.identificacion_credito_entidad)) {
        this.identificacion_credito_entidad = data().deepCopy(fields()[0].schema(), other.identificacion_credito_entidad);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tipo_identificacion)) {
        this.tipo_identificacion = data().deepCopy(fields()[1].schema(), other.tipo_identificacion);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.numero_identificacion)) {
        this.numero_identificacion = data().deepCopy(fields()[2].schema(), other.numero_identificacion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.clave_atributo)) {
        this.clave_atributo = data().deepCopy(fields()[3].schema(), other.clave_atributo);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.valor_atributo)) {
        this.valor_atributo = data().deepCopy(fields()[4].schema(), other.valor_atributo);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'identificacion_credito_entidad' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdentificacionCreditoEntidad() {
      return identificacion_credito_entidad;
    }


    /**
      * Sets the value of the 'identificacion_credito_entidad' field.
      * @param value The value of 'identificacion_credito_entidad'.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder setIdentificacionCreditoEntidad(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.identificacion_credito_entidad = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'identificacion_credito_entidad' field has been set.
      * @return True if the 'identificacion_credito_entidad' field has been set, false otherwise.
      */
    public boolean hasIdentificacionCreditoEntidad() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'identificacion_credito_entidad' field.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder clearIdentificacionCreditoEntidad() {
      identificacion_credito_entidad = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipo_identificacion' field.
      * @return The value.
      */
    public co.com.muric.entities.model.avro.tipo_ident getTipoIdentificacion() {
      return tipo_identificacion;
    }


    /**
      * Sets the value of the 'tipo_identificacion' field.
      * @param value The value of 'tipo_identificacion'.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder setTipoIdentificacion(co.com.muric.entities.model.avro.tipo_ident value) {
      validate(fields()[1], value);
      this.tipo_identificacion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo_identificacion' field has been set.
      * @return True if the 'tipo_identificacion' field has been set, false otherwise.
      */
    public boolean hasTipoIdentificacion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tipo_identificacion' field.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder clearTipoIdentificacion() {
      tipo_identificacion = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero_identificacion' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumeroIdentificacion() {
      return numero_identificacion;
    }


    /**
      * Sets the value of the 'numero_identificacion' field.
      * @param value The value of 'numero_identificacion'.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder setNumeroIdentificacion(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.numero_identificacion = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'numero_identificacion' field has been set.
      * @return True if the 'numero_identificacion' field has been set, false otherwise.
      */
    public boolean hasNumeroIdentificacion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'numero_identificacion' field.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder clearNumeroIdentificacion() {
      numero_identificacion = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'clave_atributo' field.
      * @return The value.
      */
    public int getClaveAtributo() {
      return clave_atributo;
    }


    /**
      * Sets the value of the 'clave_atributo' field.
      * @param value The value of 'clave_atributo'.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder setClaveAtributo(int value) {
      validate(fields()[3], value);
      this.clave_atributo = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'clave_atributo' field has been set.
      * @return True if the 'clave_atributo' field has been set, false otherwise.
      */
    public boolean hasClaveAtributo() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'clave_atributo' field.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder clearClaveAtributo() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'valor_atributo' field.
      * @return The value.
      */
    public java.lang.CharSequence getValorAtributo() {
      return valor_atributo;
    }


    /**
      * Sets the value of the 'valor_atributo' field.
      * @param value The value of 'valor_atributo'.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder setValorAtributo(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.valor_atributo = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'valor_atributo' field has been set.
      * @return True if the 'valor_atributo' field has been set, false otherwise.
      */
    public boolean hasValorAtributo() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'valor_atributo' field.
      * @return This builder.
      */
    public co.com.muric.entities.model.avro.Demografico.Builder clearValorAtributo() {
      valor_atributo = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Demografico build() {
      try {
        Demografico record = new Demografico();
        record.identificacion_credito_entidad = fieldSetFlags()[0] ? this.identificacion_credito_entidad : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.tipo_identificacion = fieldSetFlags()[1] ? this.tipo_identificacion : (co.com.muric.entities.model.avro.tipo_ident) defaultValue(fields()[1]);
        record.numero_identificacion = fieldSetFlags()[2] ? this.numero_identificacion : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.clave_atributo = fieldSetFlags()[3] ? this.clave_atributo : (java.lang.Integer) defaultValue(fields()[3]);
        record.valor_atributo = fieldSetFlags()[4] ? this.valor_atributo : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Demografico>
    WRITER$ = (org.apache.avro.io.DatumWriter<Demografico>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Demografico>
    READER$ = (org.apache.avro.io.DatumReader<Demografico>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.identificacion_credito_entidad);

    out.writeEnum(this.tipo_identificacion.ordinal());

    out.writeString(this.numero_identificacion);

    out.writeInt(this.clave_atributo);

    out.writeString(this.valor_atributo);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.identificacion_credito_entidad = in.readString(this.identificacion_credito_entidad instanceof Utf8 ? (Utf8)this.identificacion_credito_entidad : null);

      this.tipo_identificacion = co.com.muric.entities.model.avro.tipo_ident.values()[in.readEnum()];

      this.numero_identificacion = in.readString(this.numero_identificacion instanceof Utf8 ? (Utf8)this.numero_identificacion : null);

      this.clave_atributo = in.readInt();

      this.valor_atributo = in.readString(this.valor_atributo instanceof Utf8 ? (Utf8)this.valor_atributo : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.identificacion_credito_entidad = in.readString(this.identificacion_credito_entidad instanceof Utf8 ? (Utf8)this.identificacion_credito_entidad : null);
          break;

        case 1:
          this.tipo_identificacion = co.com.muric.entities.model.avro.tipo_ident.values()[in.readEnum()];
          break;

        case 2:
          this.numero_identificacion = in.readString(this.numero_identificacion instanceof Utf8 ? (Utf8)this.numero_identificacion : null);
          break;

        case 3:
          this.clave_atributo = in.readInt();
          break;

        case 4:
          this.valor_atributo = in.readString(this.valor_atributo instanceof Utf8 ? (Utf8)this.valor_atributo : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










