/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum estado implements org.apache.avro.generic.GenericEnumSymbol<estado> {
  _0, _1, _2, _3, _4, _5, _6, _7, _8  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"estado\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"_0\",\"_1\",\"_2\",\"_3\",\"_4\",\"_5\",\"_6\",\"_7\",\"_8\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
