/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum estado_reg implements org.apache.avro.generic.GenericEnumSymbol<estado_reg> {
  N000001, N000R01, N000R02, N000R03, N000R04, N000R05  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"estado_reg\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"N000001\",\"N000R01\",\"N000R02\",\"N000R03\",\"N000R04\",\"N000R05\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
