/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum modalidad_c implements org.apache.avro.generic.GenericEnumSymbol<modalidad_c> {
  _1, _2, _3, _4  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"modalidad_c\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"_1\",\"_2\",\"_3\",\"_4\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
