/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum moneda implements org.apache.avro.generic.GenericEnumSymbol<moneda> {
  COP, UVR, USD, EUR, GBP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"moneda\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"COP\",\"UVR\",\"USD\",\"EUR\",\"GBP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
