/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum periodo_g implements org.apache.avro.generic.GenericEnumSymbol<periodo_g> {
  _0, _1, _2, _3, _4  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"periodo_g\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"_0\",\"_1\",\"_2\",\"_3\",\"_4\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
