/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.com.muric.entities.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum tipo_t implements org.apache.avro.generic.GenericEnumSymbol<tipo_t> {
  ANA, CEC, CECUVR, CODR, CORRA, CRCDT, DEV, DTF, DTF180, DTF360, DTFE, DTFP, ENA, EUDO, ESTR, FS, HNA, IB1, IB3, IB6, IBE, IBR, IIBR, IPC, IPC1, IPC2, IPC3, IPC4, IPCS5, IPCS6, IPM, ITF, ITUS, LIB1, LIB2, LIB3, LIB4, LIB5, OTR, PRIM, RF5, RFC, RFD, SRN, SOF, SOF1, SOF2, SOF3, SOF6, SOF12, SSI, SNA, TBBT, TBS, TBS2, TBSA, TBSB, TBSD, TBSM, TBSS, TBST, TBTA, TCC, TDESC, TDTA, TEBR, TES, TES1, TES2, TES3, VUVR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"tipo_t\",\"namespace\":\"co.com.muric.entities.model.avro\",\"symbols\":[\"ANA\",\"CEC\",\"CECUVR\",\"CODR\",\"CORRA\",\"CRCDT\",\"DEV\",\"DTF\",\"DTF180\",\"DTF360\",\"DTFE\",\"DTFP\",\"ENA\",\"EUDO\",\"ESTR\",\"FS\",\"HNA\",\"IB1\",\"IB3\",\"IB6\",\"IBE\",\"IBR\",\"IIBR\",\"IPC\",\"IPC1\",\"IPC2\",\"IPC3\",\"IPC4\",\"IPCS5\",\"IPCS6\",\"IPM\",\"ITF\",\"ITUS\",\"LIB1\",\"LIB2\",\"LIB3\",\"LIB4\",\"LIB5\",\"OTR\",\"PRIM\",\"RF5\",\"RFC\",\"RFD\",\"SRN\",\"SOF\",\"SOF1\",\"SOF2\",\"SOF3\",\"SOF6\",\"SOF12\",\"SSI\",\"SNA\",\"TBBT\",\"TBS\",\"TBS2\",\"TBSA\",\"TBSB\",\"TBSD\",\"TBSM\",\"TBSS\",\"TBST\",\"TBTA\",\"TCC\",\"TDESC\",\"TDTA\",\"TEBR\",\"TES\",\"TES1\",\"TES2\",\"TES3\",\"VUVR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
